name: mockito_mocktail_migration_helper
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  analyzer: ^4.3.0
  collection: ^1.16.0

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.0.0
  mockito: ^5.2.0
  mocktail: ^0.3.0
  path: ^1.8.2
  test: ^1.16.0
